import { Color } from "lib";

export const strokeColors: { [color in Color]: string } = {
  brand: "stroke-tremor-brand-default",
  slate: "stroke-slate-500",
  gray: "stroke-gray-500",
  zinc: "stroke-zinc-500",
  neutral: "stroke-neutral-500",
  stone: "stroke-stone-500",
  red: "stroke-red-500",
  orange: "stroke-orange-500",
  amber: "stroke-amber-500",
  yellow: "stroke-yellow-500",
  lime: "stroke-lime-500",
  green: "stroke-green-500",
  emerald: "stroke-emerald-500",
  teal: "stroke-teal-500",
  cyan: "stroke-cyan-500",
  sky: "stroke-sky-500",
  blue: "stroke-blue-500",
  indigo: "stroke-indigo-500",
  violet: "stroke-violet-500",
  purple: "stroke-purple-500",
  fuchsia: "stroke-fuchsia-500",
  pink: "stroke-pink-500",
  rose: "stroke-rose-500",
};

export const fillColors: { [color in Color]: string } = {
  brand: "fill-tremor-brand-default",
  slate: "fill-slate-500",
  gray: "fill-gray-500",
  zinc: "fill-zinc-500",
  neutral: "fill-neutral-500",
  stone: "fill-stone-500",
  red: "fill-red-500",
  orange: "fill-orange-500",
  amber: "fill-amber-500",
  yellow: "fill-yellow-500",
  lime: "fill-lime-500",
  green: "fill-green-500",
  emerald: "fill-emerald-500",
  teal: "fill-teal-500",
  cyan: "fill-cyan-500",
  sky: "fill-sky-500",
  blue: "fill-blue-500",
  indigo: "fill-indigo-500",
  violet: "fill-violet-500",
  purple: "fill-purple-500",
  fuchsia: "fill-fuchsia-500",
  pink: "fill-pink-500",
  rose: "fill-rose-500",
};

export const textColors: { [color in Color]: string } = {
  brand: "text-tremor-brand-default",
  slate: "text-slate-500",
  gray: "text-gray-500",
  zinc: "text-zinc-500",
  neutral: "text-neutral-500",
  stone: "text-stone-500",
  red: "text-red-500",
  orange: "text-orange-500",
  amber: "text-amber-500",
  yellow: "text-yellow-500",
  lime: "text-lime-500",
  green: "text-green-500",
  emerald: "text-emerald-500",
  teal: "text-teal-500",
  cyan: "text-cyan-500",
  sky: "text-sky-500",
  blue: "text-blue-500",
  indigo: "text-indigo-500",
  violet: "text-violet-500",
  purple: "text-purple-500",
  fuchsia: "text-fuchsia-500",
  pink: "text-pink-500",
  rose: "text-rose-500",
};
