name: "Build"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  push:
    branches:
      - "**"
      - "!main"

jobs:
  build:
    name: Build dist
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - name: install react
        run: npm i react --legacy-peer-deps
      - name: install dependencies
        run: npm ci --legacy-peer-deps
      - name: lint checks
        run: npm run lint
      - name: unit tests
        run: npm run tests
      - name: build
        run: npm run build
